import "../globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Link from "next/link";
import Menu from "./Menu";
import { getCopywriteContent, getExtraPages } from "@/sanity/sanity-utils";
import Socials from "./Socials";
import Logo from "./Logo";

const poppins = Poppins({
  weight: ["400", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Ashlie White",
  description: "Generated by Nadya Corscadden",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const extraPages = await getExtraPages();
  const copywriteObj = await getCopywriteContent();
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <header>
          <div className="flex flex-col items-center justify-center">
            <div className="flex flex-row justify-between w-screen">
              <Logo />
              <Socials />
            </div>
            <Menu extraPages={extraPages} />
          </div>
        </header>
        <main className="max-w-7xl mx-auto px-5">{children}</main>
        <footer>
          <div className="flex flex-col text-center bg-PLATINUM-400 p-3 mt-5">
            <div>
              <div>{copywriteObj?.copywrite}</div>
              <Link href="/privacy" className="m-2">
                Privacy Policy
              </Link>
              <Link href="/terms" className="m-2">
                Terms and Conditions
              </Link>
            </div>
            <div className="">
              Website created by{" "}
              <a href="https://www.nadyacorscadden.com" target="_blank">
                Nadya Corscadden
              </a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
